// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFCDKG9szBe5s1XIqJpTVJ4wQx6Y103Uo',
    appId: '1:716530752125:android:f3c623d47f9bfbc9fc2f14',
    messagingSenderId: '716530752125',
    projectId: 'exam-app-dfbb9',
    storageBucket: 'exam-app-dfbb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0x5vpGvOyJwF4EIrUd6G7y8Zyph-gW-g',
    appId: '1:716530752125:ios:6c70f1e924d924bdfc2f14',
    messagingSenderId: '716530752125',
    projectId: 'exam-app-dfbb9',
    storageBucket: 'exam-app-dfbb9.appspot.com',
    androidClientId: '716530752125-cgmtelqnkgh418v6aefut5o60g3m4rks.apps.googleusercontent.com',
    iosClientId: '716530752125-76pljo5h5cq0etu1bdmu7i6eufb9daus.apps.googleusercontent.com',
    iosBundleId: 'com.syedi.azanreminder',
  );
}
